"""Regenerate the static news links block in news/index.html from news-data.js.

The block between the static-news markers is real HTML served to crawlers;
the page's own JS replaces it with the card grid on load. Also runs as a
Claude Code PostToolUse hook via --hook: reads the tool-call JSON from stdin
and only regenerates when the edited file was news-data.js.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA_FILE = ROOT / "news-data.js"
PAGE_FILE = ROOT / "news" / "index.html"

START_MARKER = "<!-- static-news:start - generated by generate-news-links.py, do not edit by hand -->"
END_MARKER = "<!-- static-news:end -->"

REQUIRED_FIELDS = ("slug", "title", "dateDisplay", "date")


def fail(msg):
    print(f"generate-news-links.py: ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def parse_posts(js_text):
    array_match = re.search(r"NEWS_POSTS\s*=\s*\[(.*?)^\];", js_text, re.S | re.M)
    if not array_match:
        fail("could not find NEWS_POSTS array in news-data.js")
    posts = []
    for block in re.findall(r"\{(.*?)\}", array_match.group(1), re.S):
        post = {}
        for field in REQUIRED_FIELDS:
            m = re.search(r"\b" + field + r":\s*'((?:[^'\\]|\\.)*)'", block)
            if not m:
                fail(f"post #{len(posts) + 1} is missing required field '{field}'")
            post[field] = m.group(1).replace("\\'", "'")
        posts.append(post)
    if not posts:
        fail("no posts found in NEWS_POSTS")
    return sorted(posts, key=lambda p: p["date"], reverse=True)


def escape_html(text):
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def build_block(posts):
    lines = [START_MARKER]
    for p in posts:
        lines.append(
            f'      <a href="{p["slug"]}">{escape_html(p["title"])} ({p["dateDisplay"]})</a>'
        )
    lines.append("      " + END_MARKER)
    return "\n".join(lines)


def regenerate():
    posts = parse_posts(DATA_FILE.read_text(encoding="utf-8"))
    page = PAGE_FILE.read_text(encoding="utf-8")
    if START_MARKER not in page or END_MARKER not in page:
        fail("static-news markers not found in news/index.html")
    pattern = re.compile(re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.S)
    new_page = pattern.sub(lambda _: build_block(posts), page, count=1)
    if new_page != page:
        PAGE_FILE.write_text(new_page, encoding="utf-8", newline="\n")
        print(f"Updated static news links ({len(posts)} articles).")
    else:
        print(f"Static news links already up to date ({len(posts)} articles).")


def main():
    if "--hook" in sys.argv:
        try:
            payload = json.loads(sys.stdin.buffer.read().decode("utf-8-sig"))
        except (json.JSONDecodeError, ValueError):
            sys.exit(0)  # no/invalid hook payload - not an edit we care about
        file_path = str(payload.get("tool_input", {}).get("file_path", ""))
        if not file_path.replace("\\", "/").endswith("news-data.js"):
            sys.exit(0)
    regenerate()


if __name__ == "__main__":
    main()
