"""Regenerate the static course curriculum block in course/index.html from course-data.js.

The block between the static-course markers is real HTML served to crawlers and to
anyone without JavaScript: every one of the 35 lessons is a plain <a href> link.
course-dashboard.js does not rebuild it - it only attaches the accordion toggle
handlers to the markup this script writes, so this file is the single renderer of
the guest curriculum.

NOTE: keep in sync - the unit/lesson markup below mirrors the class names used by
renderUnits() in course-dashboard.js and styled in course-dashboard.css. If those
class names change, change them here too.

Also runs as a Claude Code PostToolUse hook via --hook: reads the tool-call JSON
from stdin and only regenerates when the edited file was course-data.js.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA_FILE = ROOT / "course-data.js"
PAGE_FILE = ROOT / "course" / "index.html"
LESSON_DIR = ROOT / "course"

START_MARKER = "<!-- static-course -->"
END_MARKER = "<!-- /static-course -->"

UNIT_RE = re.compile(
    r"\n\s*id:\s*(\d+),\s*\n\s*title:\s*\"((?:[^\"\\]|\\.)*)\"",
)
LESSON_RE = re.compile(
    r"\n\s*id:\s*\"(\d+)-(\d+)\",\s*"
    r"\n\s*slug:\s*\"([^\"]+)\",\s*"
    r"\n\s*title:\s*\"((?:[^\"\\]|\\.)*)\",\s*"
    r"\n\s*duration:\s*\"([^\"]+)\"",
)


def fail(msg):
    print(f"generate-course-links.py: ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def unescape_js(text):
    return text.replace('\\"', '"').replace("\\'", "'").replace("\\\\", "\\")


def plain(text):
    """House style: no em dashes or en dashes in page copy."""
    return text.replace("—", "-").replace("–", "-")


def escape_html(text):
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def parse_units(js_text):
    array_match = re.search(r"COURSE_UNITS\s*=\s*\[(.*?)^\];", js_text, re.S | re.M)
    if not array_match:
        fail("could not find COURSE_UNITS array in course-data.js")
    body = array_match.group(1)

    units = {}
    order = []
    for m in UNIT_RE.finditer(body):
        uid = int(m.group(1))
        if uid in units:
            fail(f"duplicate unit id {uid} in course-data.js")
        units[uid] = {"id": uid, "title": unescape_js(m.group(2)), "lessons": []}
        order.append(uid)
    if not units:
        fail("no units found in COURSE_UNITS")

    lessons = 0
    for m in LESSON_RE.finditer(body):
        uid = int(m.group(1))
        if uid not in units:
            fail(f"lesson {m.group(1)}-{m.group(2)} refers to unknown unit {uid}")
        units[uid]["lessons"].append(
            {
                "id": f"{m.group(1)}-{m.group(2)}",
                "slug": m.group(3),
                "title": unescape_js(m.group(4)),
                "duration": m.group(5),
            }
        )
        lessons += 1

    for uid in order:
        if not units[uid]["lessons"]:
            fail(f"unit {uid} has no parsable lessons")

    missing = [
        l["slug"]
        for uid in order
        for l in units[uid]["lessons"]
        if not (LESSON_DIR / f"{l['slug']}.html").exists()
    ]
    if missing:
        fail("lesson pages missing for slugs: " + ", ".join(missing))

    return [units[uid] for uid in order], lessons


def build_block(units):
    lines = [
        START_MARKER,
        "        <!-- Generated by generate-course-links.py from course-data.js - do not edit by hand -->",
    ]
    for unit in units:
        title = escape_html(plain(unit["title"]))
        count = len(unit["lessons"])
        lines += [
            '        <div class="cd-unit open">',
            '          <div class="cd-unit-header" role="button" aria-expanded="true" tabindex="0">',
            f'            <div class="cd-unit-num">{unit["id"]}</div>',
            '            <div class="cd-unit-info">',
            f'              <div class="cd-unit-title">Unit {unit["id"]} - {title}</div>',
            f'              <div class="cd-unit-meta">{count} lesson{"s" if count != 1 else ""}</div>',
            "            </div>",
            '            <span class="material-symbols-outlined cd-unit-chevron" aria-hidden="true">expand_more</span>',
            "          </div>",
            '          <div class="cd-unit-lessons">',
        ]
        for lesson in unit["lessons"]:
            lesson_title = escape_html(plain(lesson["title"]))
            lines += [
                f'            <a class="cd-lesson-row" href="/course/{lesson["slug"]}">',
                '              <div class="cd-lesson-check">',
                '                <span class="material-symbols-outlined" aria-hidden="true">check</span>',
                "              </div>",
                f'              <span class="cd-lesson-title">{lesson_title}</span>',
                f'              <span class="cd-lesson-duration">{lesson["duration"]}</span>',
                "            </a>",
            ]
        lines += ["          </div>", "        </div>"]
    lines.append("        " + END_MARKER)
    return "\n".join(lines)


def regenerate():
    units, lesson_count = parse_units(DATA_FILE.read_text(encoding="utf-8"))
    page = PAGE_FILE.read_text(encoding="utf-8")
    if START_MARKER not in page or END_MARKER not in page:
        fail("static-course markers not found in course/index.html")
    pattern = re.compile(re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.S)
    new_page = pattern.sub(lambda _: build_block(units), page, count=1)

    if new_page != page:
        PAGE_FILE.write_text(new_page, encoding="utf-8", newline="\n")
        print(
            f"Updated static course links ({lesson_count} lessons across {len(units)} units)."
        )
    else:
        print(
            f"Static course links already up to date ({lesson_count} lessons across {len(units)} units)."
        )

    # Warn if the page's own copy drifts from the data.
    warnings = []
    if f"{lesson_count} lessons" not in new_page:
        warnings.append(f"page does not mention '{lesson_count} lessons'")
    if f"{len(units)} units" not in new_page:
        warnings.append(f"page does not mention '{len(units)} units'")
    for w in warnings:
        print(f"generate-course-links.py: WARNING: {w}", file=sys.stderr)


def main():
    if "--hook" in sys.argv:
        try:
            payload = json.loads(sys.stdin.buffer.read().decode("utf-8-sig"))
        except (json.JSONDecodeError, ValueError):
            sys.exit(0)  # no/invalid hook payload - not an edit we care about
        file_path = str(payload.get("tool_input", {}).get("file_path", ""))
        if not file_path.replace("\\", "/").endswith("course-data.js"):
            sys.exit(0)
    regenerate()


if __name__ == "__main__":
    main()
