"""Regenerate everything on igaming-compliance.html that is derived from data.

Four generated artefacts, all built from the REGULATIONS array in
igaming-compliance.js so none of them can drift from the source:

  1. the static regulation rows between the static-regs markers (real HTML for
     crawlers; the page's refreshTable() re-renders the same markup on load),
  2. the jurisdiction index and per-jurisdiction anchor sections between the
     static-jur markers,
  3. igaming-regulations.json - the machine-readable export of the database,
  4. the regulation/jurisdiction counts in the page copy, meta and llms.txt,
     plus the FAQPage JSON-LD, which is rebuilt from the visible FAQ so the
     schema always matches the on-page wording word for word.

Runs as a Claude Code PostToolUse hook via --hook: reads the tool-call JSON
from stdin and only regenerates when the edited file was igaming-compliance.js.

Requires node on PATH: the data arrays reference JS constants, so the rows are
rendered by node using code copied verbatim from refreshTable().
"""
import html as html_mod
import json
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA_FILE = ROOT / "igaming-compliance.js"
PAGE_FILE = ROOT / "igaming-compliance.html"
LLMS_FILE = ROOT / "llms.txt"
INDEX_JS_FILE = ROOT / "index.js"
JSON_FILE = ROOT / "igaming-regulations.json"

START_MARKER = "<!-- static-regs:start - generated by generate-compliance-table.py, do not edit by hand -->"
END_MARKER = "<!-- static-regs:end -->"
JUR_START_MARKER = "<!-- static-jur:start - generated by generate-compliance-table.py, do not edit by hand -->"
JUR_END_MARKER = "<!-- static-jur:end -->"

# Sentinels around the row markup that is duplicated between refreshTable() in
# igaming-compliance.js and NODE_RENDER below. The two blocks must be byte
# identical -- check_row_template() fails the build if they ever diverge.
ROW_START = "// row-template:start"
ROW_END = "// row-template:end"

# The renderRow() body below is copied verbatim from refreshTable() in
# igaming-compliance.js -- keep in sync if the table markup ever changes.
NODE_RENDER = r"""
const fs = require('fs');
const src = fs.readFileSync(process.argv[1], 'utf8');
const start = src.indexOf('const REGULATIONS');
const end = src.indexOf('];', start);
if (start === -1 || end === -1) {
  console.error('REGULATIONS array not found');
  process.exit(1);
}
const { REGULATIONS, COUNTRY_META } = new Function(
  src.slice(0, end + 2) + '; return { REGULATIONS, COUNTRY_META };'
)();

function catLabel(cat) {
  const labels = {
    gambling: 'Gambling',
    aml: 'AML / CFT',
    data: 'Data Protection',
    financial: 'Financial',
    digital: 'Digital & AI',
    advertising: 'Advertising',
    standards: 'Standards',
  };
  return labels[cat] || cat;
}

function escHtml(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// Body indented to 4 spaces so it matches refreshTable() byte for byte.
function renderRow(reg) {
    // row-template:start
    let jurisdiction;
    if (reg.region === 'eu-wide' || reg.region === 'global') {
      jurisdiction = reg.region === 'eu-wide' ? '🇪🇺 EU / EEA' : '🌐 Global';
    } else if (reg.countries.length > 3) {
      const first = reg.countries.slice(0, 2).map(c => (COUNTRY_META[c]?.flag || '') + ' ' + (COUNTRY_META[c]?.name || c)).join(', ');
      jurisdiction = `${first} +${reg.countries.length - 2} more`;
    } else {
      jurisdiction = reg.countries.map(c => (COUNTRY_META[c]?.flag || '') + ' ' + (COUNTRY_META[c]?.name || c)).join(', ');
    }

    return `<tr id="reg-${escHtml(reg.id)}">
      <td>
        <span class="igc-reg-name">${escHtml(reg.name)}</span>
        <span class="igc-reg-note">${escHtml(reg.notes)}</span>
      </td>
      <td>${escHtml(jurisdiction)}</td>
      <td><span class="igc-badge igc-badge-${reg.category}">${catLabel(reg.category)}</span></td>
      <td>
        <a class="igc-table-link" href="${reg.url}" target="_blank" rel="noopener noreferrer">
          <span class="material-symbols-outlined">open_in_new</span>Official
        </a>
      </td>
    </tr>`;
    // row-template:end
}

const rows = REGULATIONS.map(renderRow).join('');

// ── JURISDICTION GROUPS ──────────────────────────────────────────────────────

function slugify(str) {
  return String(str)
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

const wideRegs = REGULATIONS.filter(r => r.region === 'eu-wide');
const globalRegs = REGULATIONS.filter(r => r.region === 'global');
const localRegs = REGULATIONS.filter(r => r.region !== 'eu-wide' && r.region !== 'global');

const isoCodes = [...new Set(REGULATIONS.flatMap(r => r.countries))];
const countries = isoCodes
  .map(iso => ({
    iso,
    name: (COUNTRY_META[iso] || {}).name || iso,
    flag: (COUNTRY_META[iso] || {}).flag || '',
  }))
  .sort((a, b) => a.name.localeCompare(b.name, 'en'));

const groups = [
  { slug: 'eu-eea', flag: '🇪🇺', name: 'EU / EEA-wide', regs: wideRegs, kind: 'eu-wide' },
  { slug: 'global', flag: '🌐', name: 'Global standards', regs: globalRegs, kind: 'global' },
  ...countries.map(c => ({
    slug: slugify(c.name),
    flag: c.flag,
    name: c.name,
    iso: c.iso,
    regs: localRegs.filter(r => r.countries.includes(c.iso)),
    wide: wideRegs.filter(r => r.countries.includes(c.iso)).length,
    global: globalRegs.filter(r => r.countries.includes(c.iso)).length,
    kind: 'country',
  })),
];

const slugs = new Set();
groups.forEach(g => {
  if (slugs.has(g.slug)) {
    console.error('duplicate jurisdiction slug: ' + g.slug);
    process.exit(1);
  }
  slugs.add(g.slug);
});

function groupTotal(g) {
  return g.kind === 'country' ? g.regs.length + g.wide + g.global : g.regs.length;
}

function plural(n, word) {
  return n + ' ' + word + (n === 1 ? '' : 's');
}

const indexLinks = groups.map(g => `<a class="igc-jur-index-link" href="#jurisdiction-${g.slug}" ` +
  `aria-label="${escHtml(g.name)} - ${plural(groupTotal(g), 'regulation')}">` +
  `<span aria-hidden="true">${g.flag}</span>${escHtml(g.name)}` +
  `<span class="igc-jur-index-count">${groupTotal(g)}</span></a>`).join('\n        ');

function regItem(reg) {
  return `<li class="igc-jur-item">
              <a class="igc-jur-reg" href="#reg-${escHtml(reg.id)}">${escHtml(reg.name)}</a>
              <span class="igc-badge igc-badge-${reg.category}">${catLabel(reg.category)}</span>
              <span class="igc-jur-note">${escHtml(reg.notes)}</span>
            </li>`;
}

function alsoLine(g) {
  if (g.kind === 'eu-wide') {
    return `<p class="igc-jur-also">These apply across the EU and EEA on top of each member state's own gambling rules.</p>`;
  }
  if (g.kind === 'global') {
    return `<p class="igc-jur-also">International standards and certification schemes that operators meet regardless of licence.</p>`;
  }
  const parts = [];
  if (g.wide) parts.push(`<a href="#jurisdiction-eu-eea">${plural(g.wide, 'EU / EEA-wide framework')}</a>`);
  if (g.global) parts.push(`<a href="#jurisdiction-global">${plural(g.global, 'global standard')}</a>`);
  if (!parts.length) return '';
  if (!g.regs.length) {
    return `<p class="igc-jur-also">The ${parts.join(' and ')} still apply in ${escHtml(g.name)}.</p>`;
  }
  return `<p class="igc-jur-also">Plus ${parts.join(' and ')} that also apply in ${escHtml(g.name)}.</p>`;
}

function filterLink(g) {
  const label = ` aria-label="Filter the database to ${escHtml(g.name)}"`;
  if (g.kind === 'country') {
    return `<a class="igc-jur-filter" href="#igc-database" data-jur-search="${escHtml(g.name)}"${label}>Filter the database</a>`;
  }
  return `<a class="igc-jur-filter" href="#igc-database" data-jur-region="${g.kind}"${label}>Filter the database</a>`;
}

const sections = groups.map(g => {
  const body = g.regs.length
    ? `<ul class="igc-jur-list">
            ${g.regs.map(regItem).join('\n            ')}
          </ul>`
    : `<p class="igc-jur-empty">No gambling legislation specific to ${escHtml(g.name)} is tracked here yet.</p>`;
  const also = alsoLine(g);
  return `<section class="igc-jur" id="jurisdiction-${g.slug}">
          <h3 class="igc-jur-name"><span class="igc-jur-flag" aria-hidden="true">${g.flag}</span>${escHtml(g.name)}</h3>
          <p class="igc-jur-meta"><span>${plural(groupTotal(g), 'regulation')} apply</span>${filterLink(g)}</p>
          ${body}${also ? '\n          ' + also : ''}
        </section>`;
}).join('\n        ');

const jurBlock = `<nav class="igc-jur-index" aria-label="Jurisdiction index">
        ${indexLinks}
      </nav>
      <div class="igc-jur-grid">
        ${sections}
      </div>`;

// ── MACHINE-READABLE EXPORT ──────────────────────────────────────────────────

const jurisdictions = new Set();
REGULATIONS.forEach(r =>
  (Array.isArray(r.countries) ? r.countries : [r.countries]).forEach(c => jurisdictions.add(c))
);

const PAGE_URL = 'https://johnb.io/igaming-compliance';

const dataset = {
  name: 'iGaming Global Regulatory Compliance Database',
  description: `${REGULATIONS.length} iGaming regulations, directives and licensing frameworks tracked across ${jurisdictions.size} jurisdictions, covering gambling-specific law, AML/CFT, data protection, financial services, digital services and AI, advertising restrictions and testing standards.`,
  url: PAGE_URL,
  downloadUrl: 'https://johnb.io/igaming-regulations.json',
  license: 'https://creativecommons.org/licenses/by/4.0/',
  creator: { name: 'John Bowman', url: 'https://johnb.io/about' },
  publisher: { name: 'JohnB.io', url: 'https://johnb.io' },
  dateModified: 'DATE_MODIFIED_PLACEHOLDER',
  regulationCount: REGULATIONS.length,
  jurisdictionCount: jurisdictions.size,
  categories: [...new Set(REGULATIONS.map(r => r.category))].map(id => ({ id, label: catLabel(id) })),
  regions: [...new Set(REGULATIONS.map(r => r.region))],
  jurisdictions: groups.map(g => ({
    code: g.kind === 'country' ? g.iso : (g.kind === 'eu-wide' ? 'EU-EEA' : 'GLOBAL'),
    name: g.name,
    slug: g.slug,
    url: `${PAGE_URL}#jurisdiction-${g.slug}`,
    regulationCount: groupTotal(g),
    jurisdictionSpecificCount: g.regs.length,
  })),
  regulations: REGULATIONS.map(reg => ({
    id: reg.id,
    name: reg.name,
    category: reg.category,
    categoryLabel: catLabel(reg.category),
    region: reg.region,
    jurisdictionCodes: reg.countries,
    jurisdictionNames: reg.countries.map(c => (COUNTRY_META[c] || {}).name || c),
    summary: reg.notes || '',
    officialUrl: reg.url,
    pageUrl: `${PAGE_URL}#reg-${reg.id}`,
  })),
};

process.stdout.write(JSON.stringify({
  rows,
  jurBlock,
  dataset,
  regCount: REGULATIONS.length,
  jurCount: jurisdictions.size,
}));
"""

# Phrases that carry the counts. {n} = regulations, {m} = jurisdictions.
# Every pattern must match at least once across the stamped segments.
PAGE_COUNT_PATTERNS = [
    (r"\d+ iGaming regulations", "{n} iGaming regulations"),
    (r"\d+ regulations, directives", "{n} regulations, directives"),
    (r"\d+ regulations tracked across \d+ jurisdictions",
     "{n} regulations tracked across {m} jurisdictions"),
    (r"across \d+ jurisdictions", "across {m} jurisdictions"),
]
LLMS_COUNT_PATTERNS = [
    (r"\d+ iGaming regulations across \d+ jurisdictions",
     "{n} iGaming regulations across {m} jurisdictions"),
]

FAQ_ITEM_RE = re.compile(
    r'<div class="faq-item">\s*<dt>(.*?)</dt>\s*<dd>(.*?)</dd>\s*</div>', re.S
)
LD_JSON_RE = re.compile(
    r'(<script type="application/ld\+json">\n)(.*?)(\n  </script>)', re.S
)
LAST_UPDATED_RE = re.compile(
    r'class="igc-last-updated".*?<time datetime="(\d{4}-\d{2}-\d{2})"', re.S
)


def fail(msg):
    print(f"generate-compliance-table.py: ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def extract_between(text, start, end, where):
    i = text.find(start)
    j = text.find(end)
    if i == -1 or j == -1 or j < i:
        fail(f"{start} / {end} markers not found or out of order in {where}")
    return text[i + len(start):j]


def check_row_template(js_source):
    """The row markup lives twice: refreshTable() and NODE_RENDER. Fail on drift."""
    from_js = extract_between(js_source, ROW_START, ROW_END, "igaming-compliance.js")
    from_py = extract_between(NODE_RENDER, ROW_START, ROW_END, "generate-compliance-table.py")
    if from_js.replace("\r\n", "\n") != from_py.replace("\r\n", "\n"):
        fail(
            "the row template in refreshTable() (igaming-compliance.js) and the copy "
            "in NODE_RENDER (generate-compliance-table.py) have diverged. Copy the "
            "block between the row-template markers from the JS into the Python "
            "script verbatim, keeping the 4-space indentation."
        )


def render_data():
    try:
        proc = subprocess.run(
            ["node", "-e", NODE_RENDER, str(DATA_FILE)],
            capture_output=True, encoding="utf-8", timeout=30,
        )
    except FileNotFoundError:
        fail("node is required on PATH to evaluate igaming-compliance.js")
    except subprocess.TimeoutExpired:
        fail("node evaluation timed out")
    if proc.returncode != 0:
        fail(f"node evaluation failed: {proc.stderr.strip()}")
    try:
        data = json.loads(proc.stdout)
    except json.JSONDecodeError:
        fail("node did not return valid JSON")
    if data["regCount"] == 0 or not data["rows"]:
        fail("no regulations parsed from igaming-compliance.js")
    if not data["jurBlock"]:
        fail("no jurisdiction sections rendered from igaming-compliance.js")
    return data


def stamp_counts(segments, patterns, n, m, where):
    for pat, repl in patterns:
        total = 0
        for i, seg in enumerate(segments):
            segments[i], count = re.subn(pat, repl.format(n=n, m=m), seg)
            total += count
        if total == 0:
            fail(f"count phrase /{pat}/ not found in {where}")
    return segments


def plain_text(fragment):
    """Visible FAQ markup -> the exact words, for the FAQPage JSON-LD."""
    text = re.sub(r"<[^>]+>", "", fragment)
    text = html_mod.unescape(text)
    return re.sub(r"\s+", " ", text).strip()


def sync_json_ld(page, page_date):
    """Rebuild the FAQPage entries from the visible FAQ and stamp dateModified."""
    faqs = FAQ_ITEM_RE.findall(page)
    if len(faqs) < 5:
        fail(f"expected at least 5 visible FAQ items, found {len(faqs)}")

    m_ld = LD_JSON_RE.search(page)
    if not m_ld:
        fail("JSON-LD block not found in igaming-compliance.html")
    try:
        graph = json.loads(m_ld.group(2))
    except json.JSONDecodeError as err:
        fail(f"JSON-LD block is not valid JSON: {err}")

    nodes = graph.get("@graph", [graph])
    faq_node = next((n for n in nodes if n.get("@type") == "FAQPage"), None)
    if faq_node is None:
        fail("no FAQPage node in the igaming-compliance.html JSON-LD graph")
    faq_node["mainEntity"] = [
        {
            "@type": "Question",
            "name": plain_text(q),
            "acceptedAnswer": {"@type": "Answer", "text": plain_text(a)},
        }
        for q, a in faqs
    ]

    dataset_node = next((n for n in nodes if n.get("@type") == "Dataset"), None)
    if dataset_node is None:
        fail("no Dataset node in the igaming-compliance.html JSON-LD graph")
    dataset_node["dateModified"] = page_date
    if not dataset_node.get("distribution"):
        fail("Dataset schema is missing its distribution (igaming-regulations.json)")

    body = json.dumps(graph, ensure_ascii=False, indent=2)
    body = "\n".join(("  " + line) if line else line for line in body.split("\n"))
    return page[:m_ld.start(2)] + body + page[m_ld.end(2):]


def regenerate():
    js_source = DATA_FILE.read_text(encoding="utf-8")
    check_row_template(js_source)

    data = render_data()
    n, m = data["regCount"], data["jurCount"]

    page = PAGE_FILE.read_text(encoding="utf-8")
    block_re = re.compile(re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.S)
    m_block = block_re.search(page)
    if not m_block:
        fail("static-regs markers not found or out of order in igaming-compliance.html")
    old_block = m_block.group(0)
    new_block = START_MARKER + "\n" + data["rows"] + "\n            " + END_MARKER

    head = page[:m_block.start()]
    tail = page[m_block.end():]
    if new_block != old_block:
        stamp = date.today().strftime("%B %Y")
        tail, count = re.subn(r"(</strong> as of )\w+ \d{4}", r"\g<1>" + stamp, tail)
        if count == 0:
            fail('"as of" stamp not found in Key Points of igaming-compliance.html')
    head, tail = stamp_counts([head, tail], PAGE_COUNT_PATTERNS, n, m, "igaming-compliance.html")
    new_page = head + new_block + tail

    jur_re = re.compile(re.escape(JUR_START_MARKER) + r".*?" + re.escape(JUR_END_MARKER), re.S)
    if not jur_re.search(new_page):
        fail("static-jur markers not found or out of order in igaming-compliance.html")
    new_page = jur_re.sub(
        lambda _: JUR_START_MARKER + "\n      " + data["jurBlock"] + "\n      " + JUR_END_MARKER,
        new_page, count=1,
    )

    m_date = LAST_UPDATED_RE.search(new_page)
    if not m_date:
        fail('"Last updated" <time datetime="..."> not found in igaming-compliance.html')
    page_date = m_date.group(1)
    new_page = sync_json_ld(new_page, page_date)

    if new_page != page:
        PAGE_FILE.write_text(new_page, encoding="utf-8", newline="\n")
        print(f"Updated igaming-compliance.html ({n} regulations, {m} jurisdictions).")
    else:
        print(f"igaming-compliance.html already up to date ({n} regulations, {m} jurisdictions).")

    dataset = data["dataset"]
    dataset["dateModified"] = page_date
    new_json = json.dumps(dataset, ensure_ascii=False, indent=2) + "\n"
    old_json = JSON_FILE.read_text(encoding="utf-8") if JSON_FILE.exists() else ""
    if new_json != old_json:
        JSON_FILE.write_text(new_json, encoding="utf-8", newline="\n")
        print(f"Wrote {JSON_FILE.name} ({len(dataset['regulations'])} regulations).")

    llms = LLMS_FILE.read_text(encoding="utf-8")
    new_llms = stamp_counts([llms], LLMS_COUNT_PATTERNS, n, m, "llms.txt")[0]
    if new_llms != llms:
        LLMS_FILE.write_text(new_llms, encoding="utf-8", newline="\n")
        print("Updated counts in llms.txt.")

    expected = f"{n} iGaming regulations across {m} jurisdictions"
    if expected not in INDEX_JS_FILE.read_text(encoding="utf-8"):
        print(
            f"WARNING: index.js tool-card description does not say '{expected}'.\n"
            "         Update the igaming-compliance entry in index.js by hand and bump\n"
            "         its ?v= version in index.html (cache rule in CLAUDE.md).",
            file=sys.stderr,
        )


def main():
    if "--hook" in sys.argv:
        try:
            payload = json.loads(sys.stdin.buffer.read().decode("utf-8-sig"))
        except (json.JSONDecodeError, ValueError):
            sys.exit(0)  # no/invalid hook payload - not an edit we care about
        file_path = str(payload.get("tool_input", {}).get("file_path", ""))
        if not file_path.replace("\\", "/").endswith("igaming-compliance.js"):
            sys.exit(0)
    regenerate()


if __name__ == "__main__":
    main()
