"""Regenerate the static regulation rows in igaming-compliance.html.

The block between the static-regs markers is real HTML served to crawlers;
the page's refreshTable() re-renders the same markup on load. Also stamps
the regulation and jurisdiction counts into the page copy/meta and llms.txt
so the published numbers cannot drift from the data. Runs as a Claude Code
PostToolUse hook via --hook: reads the tool-call JSON from stdin and only
regenerates when the edited file was igaming-compliance.js.

Requires node on PATH: the data arrays reference JS constants, so the rows
are rendered by node using code copied verbatim from refreshTable().
"""
import json
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DATA_FILE = ROOT / "igaming-compliance.js"
PAGE_FILE = ROOT / "igaming-compliance.html"
LLMS_FILE = ROOT / "llms.txt"
INDEX_JS_FILE = ROOT / "index.js"

START_MARKER = "<!-- static-regs:start - generated by generate-compliance-table.py, do not edit by hand -->"
END_MARKER = "<!-- static-regs:end -->"

# Row-building code below is copied verbatim from refreshTable() in
# igaming-compliance.js -- keep in sync if the table markup ever changes.
NODE_RENDER = r"""
const fs = require('fs');
const src = fs.readFileSync(process.argv[1], 'utf8');
const start = src.indexOf('const REGULATIONS');
const end = src.indexOf('];', start);
if (start === -1 || end === -1) {
  console.error('REGULATIONS array not found');
  process.exit(1);
}
const { REGULATIONS, COUNTRY_META } = new Function(
  src.slice(0, end + 2) + '; return { REGULATIONS, COUNTRY_META };'
)();

function catLabel(cat) {
  const labels = {
    gambling: 'Gambling',
    aml: 'AML / CFT',
    data: 'Data Protection',
    financial: 'Financial',
    digital: 'Digital & AI',
    advertising: 'Advertising',
    standards: 'Standards',
  };
  return labels[cat] || cat;
}

function escHtml(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

const rows = REGULATIONS.map(reg => {
  let jurisdiction;
  if (reg.region === 'eu-wide' || reg.region === 'global') {
    jurisdiction = reg.region === 'eu-wide' ? '🇪🇺 EU / EEA' : '🌐 Global';
  } else if (reg.countries.length > 3) {
    const first = reg.countries.slice(0, 2).map(c => (COUNTRY_META[c]?.flag || '') + ' ' + (COUNTRY_META[c]?.name || c)).join(', ');
    jurisdiction = `${first} +${reg.countries.length - 2} more`;
  } else {
    jurisdiction = reg.countries.map(c => (COUNTRY_META[c]?.flag || '') + ' ' + (COUNTRY_META[c]?.name || c)).join(', ');
  }

  return `<tr>
      <td>${escHtml(reg.name)}</td>
      <td>${escHtml(jurisdiction)}</td>
      <td><span class="igc-badge igc-badge-${reg.category}">${catLabel(reg.category)}</span></td>
      <td>
        <a class="igc-table-link" href="${reg.url}" target="_blank" rel="noopener noreferrer">
          <span class="material-symbols-outlined">open_in_new</span>Official
        </a>
      </td>
    </tr>`;
}).join('');

const jurisdictions = new Set();
REGULATIONS.forEach(r =>
  (Array.isArray(r.countries) ? r.countries : [r.countries]).forEach(c => jurisdictions.add(c))
);

process.stdout.write(JSON.stringify({
  rows,
  regCount: REGULATIONS.length,
  jurCount: jurisdictions.size,
}));
"""

# Phrases that carry the counts. {n} = regulations, {m} = jurisdictions.
# Every pattern must match at least once across the stamped segments.
PAGE_COUNT_PATTERNS = [
    (r"\d+ iGaming regulations", "{n} iGaming regulations"),
    (r"\d+ regulations, directives", "{n} regulations, directives"),
    (r"\d+ regulations tracked across \d+ jurisdictions",
     "{n} regulations tracked across {m} jurisdictions"),
    (r"across \d+ jurisdictions", "across {m} jurisdictions"),
]
LLMS_COUNT_PATTERNS = [
    (r"\d+ iGaming regulations across \d+ jurisdictions",
     "{n} iGaming regulations across {m} jurisdictions"),
]


def fail(msg):
    print(f"generate-compliance-table.py: ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def render_rows():
    try:
        proc = subprocess.run(
            ["node", "-e", NODE_RENDER, str(DATA_FILE)],
            capture_output=True, encoding="utf-8", timeout=30,
        )
    except FileNotFoundError:
        fail("node is required on PATH to evaluate igaming-compliance.js")
    except subprocess.TimeoutExpired:
        fail("node evaluation timed out")
    if proc.returncode != 0:
        fail(f"node evaluation failed: {proc.stderr.strip()}")
    try:
        data = json.loads(proc.stdout)
    except json.JSONDecodeError:
        fail("node did not return valid JSON")
    if data["regCount"] == 0 or not data["rows"]:
        fail("no regulations parsed from igaming-compliance.js")
    return data


def stamp_counts(segments, patterns, n, m, where):
    for pat, repl in patterns:
        total = 0
        for i, seg in enumerate(segments):
            segments[i], count = re.subn(pat, repl.format(n=n, m=m), seg)
            total += count
        if total == 0:
            fail(f"count phrase /{pat}/ not found in {where}")
    return segments


def regenerate():
    data = render_rows()
    n, m = data["regCount"], data["jurCount"]

    page = PAGE_FILE.read_text(encoding="utf-8")
    block_re = re.compile(re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER), re.S)
    m_block = block_re.search(page)
    if not m_block:
        fail("static-regs markers not found or out of order in igaming-compliance.html")
    old_block = m_block.group(0)
    new_block = START_MARKER + "\n" + data["rows"] + "\n            " + END_MARKER

    head = page[:m_block.start()]
    tail = page[m_block.end():]
    if new_block != old_block:
        stamp = date.today().strftime("%B %Y")
        tail, count = re.subn(r"(</strong> as of )\w+ \d{4}", r"\g<1>" + stamp, tail)
        if count == 0:
            fail('"as of" stamp not found in Key Points of igaming-compliance.html')
    head, tail = stamp_counts([head, tail], PAGE_COUNT_PATTERNS, n, m, "igaming-compliance.html")
    new_page = head + new_block + tail

    if new_page != page:
        PAGE_FILE.write_text(new_page, encoding="utf-8", newline="\n")
        print(f"Updated static regulation table ({n} regulations, {m} jurisdictions).")
    else:
        print(f"Static regulation table already up to date ({n} regulations, {m} jurisdictions).")

    llms = LLMS_FILE.read_text(encoding="utf-8")
    new_llms = stamp_counts([llms], LLMS_COUNT_PATTERNS, n, m, "llms.txt")[0]
    if new_llms != llms:
        LLMS_FILE.write_text(new_llms, encoding="utf-8", newline="\n")
        print("Updated counts in llms.txt.")

    expected = f"{n} iGaming regulations across {m} jurisdictions"
    if expected not in INDEX_JS_FILE.read_text(encoding="utf-8"):
        print(
            f"WARNING: index.js tool-card description does not say '{expected}'.\n"
            "         Update the igaming-compliance entry in index.js by hand and bump\n"
            "         its ?v= version in index.html (cache rule in CLAUDE.md).",
            file=sys.stderr,
        )


def main():
    if "--hook" in sys.argv:
        try:
            payload = json.loads(sys.stdin.buffer.read().decode("utf-8-sig"))
        except (json.JSONDecodeError, ValueError):
            sys.exit(0)  # no/invalid hook payload - not an edit we care about
        file_path = str(payload.get("tool_input", {}).get("file_path", ""))
        if not file_path.replace("\\", "/").endswith("igaming-compliance.js"):
            sys.exit(0)
    regenerate()


if __name__ == "__main__":
    main()
